// <auto-generated />
namespace ToDoListContextEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class First_Migration_Create_Category_Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_Migration_Create_Category_Task));
        
        string IMigrationMetadata.Id
        {
            get { return "201802120706328_First_Migration_Create_Category_Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
